8 addcommnets
Nicolakirk/nc_news pull request #5
Opened 2023-04-20 14:12 UTC by Nicolakirk

add comments added

2023-04-20 14:59 UTC, itskatherine requested changes
Comment adder looking good Nicola, I like your use of optimistic rendering and your CSS 🎨 
The layout of your code makes it quite difficult to read - I'd consider using a VScode extension like Prettier to format your code. 💡 
Also atm I'm able to spam multiple empty comments (they dont persist on the backend but remain on the screen in state), can you prevent the user doing this? 
Can you also add functionality so that a user can't post a comment while the previous comment is in the process of being posted by the api? Once you've added these please resubmit 📝

2023-04-20 14:59 UTC, itskatherine commented on src/components/CommentsForm.jsx
> +                console.log(inputComment);
console log begone

2023-04-20 14:59 UTC, itskatherine commented on src/components/CommentsForm.jsx
> +       (currentComments.shift()); })
We should never mutate the state in these functions, you should make a copy of the currentComments and alter that instead 👍

2023-04-20 14:59 UTC, itskatherine commented on src/components/CommentsForm.jsx
> +    setUserName("tickle122");
There's no point at which you change this state so you don't need this line.
Strictly as this isn't changed anywhere it doesn't need to be in a state 🤔

2023-04-20 14:59 UTC, itskatherine commented on src/components/CommentList.jsx
> +console.log(commentsList[1])
console logs begone

2023-04-20 14:59 UTC, itskatherine commented on src/components/CommentsForm.jsx
> +                    return ([inputComment, ...currentComments])})
Nice use of optimistic rendering

2023-04-21 08:21 UTC, popatre approved these changes
Lovely stuff - 
Small thing, but could you change this to a textarea to enable multi line comments - just incase someone wants to post a bit more of a comment.
Good to merge after that though

2023-04-21 08:21 UTC, popatre commented on src/components/CommentsForm.jsx
> +              />
Small thing, but could you change this to a textarea to enable multi line comments - just incase someone wants to post a bit more of a comment

2023-04-21 08:21 UTC, popatre commented on src/components/CommentsForm.jsx
> +              required
Nice controlled component

2023-04-21 08:35 UTC, Nicolakirk commented on src/components/CommentsForm.jsx
> +              required
Thanks

2023-04-21 08:36 UTC, merged